######################################################################
# Automatically generated by qmake (3.0) ?? 4? 11 21:34:01 2013
######################################################################

QT += xml
TEMPLATE = app
TARGET = TaoBaoAutoSdk
INCLUDEPATH += . \
               include/taobaosdk/mapper \
               include/taobaosdk/generator \
               include/taobaosdk/parser \
               include/taobaosdk/domain \
               include/taobaosdk/util \
               include/taobaosdk

# Input
HEADERS += include/taobaosdk/SdkConstants.h \
           include/taobaosdk/domain/ApiDomain.h \
           include/taobaosdk/domain/ApiField.h \
           include/taobaosdk/domain/ApiRequest.h \
           include/taobaosdk/domain/ApiResponse.h \
           include/taobaosdk/domain/BaseObject.h \
           include/taobaosdk/domain/NameObject.h \
           include/taobaosdk/generator/CppQtSdkGenerator.h \
           include/taobaosdk/generator/SdkGenerator.h \
           include/taobaosdk/mapper/CppQtTypeMapper.h \
           include/taobaosdk/mapper/TypeMapper.h \
           include/taobaosdk/parser/MetaSdkParser.h \
           include/taobaosdk/parser/SdkParser.h \
           include/taobaosdk/util/StringKit.h
SOURCES += src/main.cpp \
           src/SdkConstants.cpp \
           src/domain/ApiField.cpp \
           src/generator/CppQtSdkGenerator.cpp \
           src/generator/SdkGenerator.cpp \
           src/mapper/CppQtTypeMapper.cpp \
           src/parser/MetaSdkParser.cpp \
           src/util/StringKit.cpp
